### ISSUE TITLE
It is possible in the circle view to select one carrier multiple times

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#15]
Hey,

in the circle view it is possible to select one carrier multiple times: This means you can compare carrier 2 with carrier 2, carrier 3 and carrier 2. 

I think it would be better if you get a prompt if you try to compare one carrier with itsself.

**Comment by deadlmaster** [comment]
yep i know, working on it :) Just had not the time yet

**Comment by deadlmaster** [comment]
solved! Can be closed now.

**Comment by danielreischl** [comment]
That's great :+1: 

I think you can close it on your own the next time:) Just press close and comment instead of comment :)

**Comment by deadlmaster** [comment]
Thanks for closing, did not find the button in the message text...mhm well whatever

**Comment by danielreischl** [comment]
![image](https://cloud.githubusercontent.com/assets/18442099/15298602/6ca8aab0-1ba0-11e6-9305-adfa16f12716.png)

You're welcome :)
Instead of reopen and comment, there was close and comment.
