### ISSUE TITLE
BUG: MainPage: Red border at mouse over. 

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#19]
Not a bug to fix now I think, but if you hoover over the circles you still have a red border:

![image](https://cloud.githubusercontent.com/assets/18442099/15373531/7089d95e-1d46-11e6-8805-712301b49a1a.png)

**Comment by deadlmaster** [comment]
Hi @AMOSus,

I am not sure if this design "bug" was made on purpose. Therefore I would not label this issue as a bug but rather an "enhancement" or "question".

@shefalishukla please give feedback to this matter.

**Comment by Vick3** [comment]
Okay!! I'll try to change border color also in Green.

Thanks for your information. :)

**Comment by Vick3** [comment]
Issue solved :)

**Comment by danielreischl** [comment]
Fixed with

2d1be532bc90a0e190cf29ab581e79ac35567271
