### ISSUE TITLE
Database Schema and Software Architecture are not up2date

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#20]
With a look to the midterm release, we should update the Database Schema and software architecture. Both changed during the last weeks and are no longer up2date.

**Comment by danielreischl** [comment]
As discused earlier @Inkibus will do it

**Comment by ghost** [comment]
I'm on it

**Comment by ghost** [comment]
Both are up to date and in the wiki. For errors or further improvements please open a new thread.
