### ISSUE TITLE
Missing Project Documentation and Build Instructions

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#21]
Because of the midterm release, I think we have to create a proper project documentation and build instruction.

**Comment by danielreischl** [comment]
@alexklar @abhinavpuri  will write a brief summary about the project and requests which information we can use from our industry partner

@AMOSus Will document DataProcessing

@Vick3 @deadlmaster @shefalishukla Will document the Frontend

@TobiDo will create the the build instructions

Everything will be documented in the WIKI.

**Comment by danielreischl** [comment]
Documentation of DataProcessing should be done. Thx for the help @Inkibus

**Comment by ghost** [comment]
@shefalishukla your documentation is still missing. Please finish! The rest is done, great job guys!

**Comment by ghost** [comment]
@alexklar @abhinavpuri  Your project description is missing too.

**Comment by ghost** [comment]
@TobiDo your build instructions are missing in the README, please push ;)

**Comment by TobiDo** [comment]
Moved them to README.

**Comment by ghost** [comment]
Is this closed right?

**Comment by danielreischl** [comment]
Nope, BarChart documetnation is still missing by Shefali/Vick

**Comment by ghost** [comment]
> Nope, BarChart documetnation is still missing by Shefali/Vick

@shefalishukla and @Vick3 please provide documentation.

**Comment by alexklar** [comment]
We (the POs) posted the sumary under "General Information" but was then moved to "Home", as far as I am concerned. Is that right, @AMOSus? Cheers!

**Comment by danielreischl** [comment]
Yes that's right. It's on Home and in the readme.file!

**Comment by danielreischl** [comment]
Because @shefalishukla & @Vick3 left the project and the bar chart is currently not in scope, I close this issue.
