### ISSUE TITLE
Refactor DataProcessing file structure

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#22]
@AMOSus or @TobiDo could you please move all files in /DataProcessing/Scripts/ to /DataProcessing/ and delete the /Scripts/ folder, because there is no reason for the folder /Scripts/ as of now.

**Comment by danielreischl** [comment]
This is already done for a couple of days;

https://github.com/AMOSus/amos-ss16-proj6/commit/582a70fe57df848ce7b341d5a7c253934ed32114

**Comment by ghost** [comment]
You are right. My IDE didn't update that.
