### ISSUE TITLE
Refactoring: Renaming DataProcessing algorithms

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#23]
@TobiDo or @AMOSus:
I checked the refactoring-rename option in PyCharm and wanted to rename the algorithms in /DataProcessing/, however it showed that it would not change the code in any DOCKERFILE or anything outside of the python scripts. Therefore, it needs to be done manually.

Could you please rename the scripts dataProcessing.py and manipulateData.py and initSimulation.sh.
My suggestions would be:
dataProcessing.py -> mapInitialDataToCarrierData.py
manipulateData.py -> writeCarrierDataToDataBase.py
initSimulation.sh -> initDataProcessingSimulation.sh

**Comment by danielreischl** [comment]
dataProcessing.py -> mapInitialDataToCarrierData.py

I don't like that name. Because it is more about compressing data. Rather compressInitialData?

**Comment by ghost** [comment]
> dataProcessing.py -> mapInitialDataToCarrierData.py
> I don't like that name. Because it is more about compressing data. Rather compressInitialData?

I agree that the name doesn't give any information abut compression. It actually does both. Mapping and Compressing. Whatsoever, I think compressInitialData is also a valid name.

**Comment by danielreischl** [comment]
Done :)
