### ISSUE TITLE
REFACTORING: django helloWorld

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#24]
Hey guys,

I think we should Rename our main django app from helloWorld to something else. Any suggestions how we should name it?

And @TobiDo can you do the renaming? I don't know what excactly has to be changed.

**Comment by TobiDo** [comment]
Ah yes. Any suggestions? Otherwise I will just make up some name.

**Comment by danielreischl** [comment]
no just go ahead. maybe siemens-data-analytics. Just something related to the project.

**Comment by ghost** [comment]
@TobiDo 
Name suggestion "Rogue Vision" for the whole product. Also designed a logo and put it to the website.
