### ISSUE TITLE
ENHANCEMENT: Click on Logo should bring you back to MainPage

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#25]
Hey,

I think a click on the Logo on the TopLeft should bring you back to the MainPage. I try to click it all the time but nothing happens. I think this would increase the usability a lot.

What do u guys think?

![image](https://cloud.githubusercontent.com/assets/18442099/15453520/4bcf76ca-2019-11e6-823b-8be491483a22.png)

**Comment by ghost** [comment]
Agreed. Assign someone?

**Comment by Vick3** [comment]
Feature added: When clicking FAU Logo links to the Homepage.

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=vickyram.yahoo@gmail.com&idSignature=22

**Comment by danielreischl** [comment]
did  u also push it to git?

I don't see a commit :O

**Comment by ghost** [comment]
Me neither :(

**Comment by Vick3** [comment]
Yep, now u can check.

**Comment by ghost** [comment]
Works

**Comment by ghost** [comment]
Just checked again, it takes you back to a plain site instead of the starting page.
