### ISSUE TITLE
DYGraphs - Questions on our usage

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#26]
Hey guys,

I have a question about DYGraphs:
1. Why do we use the dev version instead of the stable version? Is there any advantage?
2. Why do we download it instead of importing it?
3. Why is dygraphs two times in our repository?

**Comment by ghost** [comment]
@shefalishukla  @Vick3 @deadlmaster

**Comment by danielreischl** [comment]
Guys, update on that?

**Comment by deadlmaster** [comment]
Second dygraph was for testing purpose, will be deleted, when the GraphExample Page is not used anymore. @TobiDo Do you need the graph example folder? If not then I would say we delete it

**Comment by danielreischl** [comment]
Why are we not using an installer like nvm?

**Comment by deadlmaster** [comment]
you mean npm? Because we did not say so. Also the dygraph lib was already downloaded into the client folder. Might as well continue this approach

**Comment by danielreischl** [comment]
Yes or something like that. Or download it manually in the build script. Some approach like that. I think this would be best practice.

Well we downloaded one out of 7? javascript libraries. In the end I don't really care but to keep the repository clean I would suggest not to store them in the repository.

**Comment by deadlmaster** [comment]
I dont mind, we can use npm as well. Let's discuss this topic in person tomorrow 

> Well we downloaded one out of 7? javascript libraries. 

nah I meant in the beginning. Right now, 3 libs are downloaded.
