### ISSUE TITLE
Reset selected carriers in Circle and Barchart view.

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#27]
When I select carrier(s) in the circle view and then go to the comparison view, then go back to the circle view to select new carriers, the carrier(s) that i have previously selected are still in the selection. 

I think the user expects the selection to be empty when he opens the circle or barchart view to select new carriers.

@shefalishukla @Vick3 @deadlmaster

**Comment by deadlmaster** [comment]
Okay I will check how to solve this issue

**Comment by alexklar** [comment]
We have added this as a user story 61 in the product backlog and will assign it later today.
