### ISSUE TITLE
Are we allowed to use the Siemens logo and Information on the demonstrator

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#28]
Hey.

are we allowed to use the siemens logo and information on the demonstrator in the documentation. Like a picture, information on carriers and drives. I'm not sure about that and I think we have to clearify with the industry partner.

**Comment by danielreischl** [comment]
Any update on this?

**Comment by ghost** [comment]
Let's ask Löwen next week, but i guess since this will be an open source product we shouldn't use the Siemens logo.

**Comment by alexklar** [comment]
Asked Löwen, he was not completely sure about it so we will discuss it in the meeting. I think he wants to see the app first and if he is happy with it he will allow us to use it :dancers:

**Comment by danielreischl** [comment]
This can be closed because as far as I know we are allowed to use it.
