### ISSUE TITLE
Loading data to Jenkins

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#29]
Hey,

we have a bit an issue here. I don't think we should push the raw data to GitHub. But we have to show the data in the running Jenkins. I think we could do that with building the docker container without github to get the data to jenkins.

But for that we would need to share the docker password. We could build the docker container locally and push it.

What do you guys think about that idea?

**Comment by TobiDo** [comment]
I agree that we shouldn't put large data sets on the GitHub. There is indeed the possibility to store data persistently on the OSR-server. So we can once build a container locally that copies the data to the server and from then on just continue as before. I could take care of that and will let you know how to access the data files.

**Comment by danielreischl** [comment]
Ah yeah that's a good idea :) I would say go for it. :)

But I think we should also discuss a file upload option. I could imagine that our industry partner will provide us new data time by time and this workaround might not be the best in this case. But this is something for later and not for now. :)

**Comment by danielreischl** [comment]
Any update on that?

**Comment by danielreischl** [comment]
Date is in jenkins but caused #36
