### ISSUE TITLE
Changing "position on drive" in data, data-processing and database

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#30]
Until now we thought that we would just get the "position on drive" in the initial data. This means that our position went to 0 and higher multiple times within one iteration. Since this is not good for representation, we calculated the "absolute position" for the carrier during the course of the iteration. We then stored BOTH values in the database (absolute and on drive)

Now that we have the final data and we are getting (against our expectations) the carrier position as "absolute position" rather than "position on drive" there is no reason for it to be calculated anymore. Should I just remove the "position on drive" from every data point? 

This is exactly how i will proceed. Should we go for a) or b)???

1) Change the compressInitialData.py so that it now:
    a) EITHER: Does NOT save the "position on drive". This also means that we lose the possibility to calculate on which drive the carrier is on during one iteration.
    b) OR: Save on which drive the carrier is on at every timestamp. This then could be represented in the graph. This would also mean, that we have huge amount of redundant data entries, so the question is do we need this?
2) Change the database model (models.py) according to a) or b)
2) Change the writeCarrierDataToDataBase.py so that it writes the correct data to the database according to a) or b)

Hoping for clarification ASAP.

Best regards,
Rene

**Comment by Inkibus** [comment]
@TobiDo @deadlmaster @Vick3 @abhinavpuri @AMOSus @alexklar @shefalishukla

**Comment by danielreischl** [comment]
I don't get the issue right now to be honest. The data is kinda clear in this matter. We don't use the positionOnDrive at all. So just remove it.  You can add on which drive it is. Could make sense for later. 

For writeCarrierDataToDataBasen.py it doesn't really matter. That's just a small change then.

**Comment by ghost** [comment]
I wan't to hear from you: Do a) or do b)

You just suggested to me: do a), but do b) because it could make sense for later.

I know it's a small change, but as long as this is not resolved i can't update the database model.

**Comment by danielreischl** [comment]
Sorry, but why does a exclude b?

Just do it this way: 
ms energy absoultePosition Drive

We can still calculate the position on the drive later if we need and don't loose anything. 

Maybe I just get your issue wrong.

**Comment by ghost** [comment]
You are right, thanks. Maybe I was not clear in my wording:

a) ms energy absoultePosition
b) ms energy absoultePosition Drive

Arguments for both:
a) Is more storage efficient and we may now need the drive every
b) We don't lose as much information

But since you have voted for b) and I don't think anyone else will participate i will go for b)

I will let you know once im don't with initialDataProcessing and the database model so you can do the writeDataToDataBase?

**Comment by danielreischl** [comment]
Ah ok now I got it :dancer: 

Yeah I would go for b. We can still remove it later. But I think @alexklar or @abhinavpuri should state if they plan to add views which would need that data.

Sure, might not be today, but will do it.

**Comment by ghost** [comment]
Data was changed everywhere.
Is this done and working @AMOSus ?

**Comment by danielreischl** [comment]
Jup.
