### ISSUE TITLE
BarChart Hover Bug

### ISSUE THREAD

**Issue by TobiDo** [AMOSus/amos-ss16-proj6#34]
BarChart shows strange behaviour: if you hover a bar, the hover-color seems to be the color of the bar left of the one you are hovering. If you hover the bar of carrier3, also the bar of carrier4 changes color.

Is this browser specific? I get this behaviour with Iceweasel and GoogleChrome.

**Comment by ghost** [comment]
Also, are bars dynamically generated due to a file or is there just a static amount for now?

**Comment by danielreischl** [comment]
I think this can be considered as done. Hovering seems to be disabled after https://github.com/AMOSus/amos-ss16-proj6/commit/b7aa3eb7fa8a8f88ee52b256943aba1d06f4c41a
