### ISSUE TITLE
Use of Javascript libs

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#35]
Hey,

how will we handle now the javascript libs? Will we save them locally, importing them in the header or will we go with another approach? We should also decide on that until tmr. I think we should deliver a reasonable product tmr. At the moment our aproach isn't clear.

This is also related to: #26

**Comment by danielreischl** [comment]
Guys, what is the situation?

**Comment by deadlmaster** [comment]
My proposal: 
Download all libs and store them inside a "libs" folder. E.g. Client/Assets/Libs

**Comment by danielreischl** [comment]
For now Dygraphs, Chart.js, papaparse and jquery are now installed by bower. All of the angular libraries are still missing. Will add them later
