### ISSUE TITLE
Since moving data to the persistent folder no data is loaded into the database

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#36]
Since we moved the data yesterday to the persistent folder, no data is loaded to the database anymorwith. 

The reason is unclear at the moment. In the test environment it is still working.

**Comment by danielreischl** [comment]
It's fixed for now but just because archiving files is deactivated. The file moving has to be fixed.

**Comment by danielreischl** [comment]
This is also causing that files are read in multiple times and we get duplicates into the database. @Inkibus will fix the datafiles moving

**Comment by ghost** [comment]
The data is added multiple times to the database for 2 reasons:
- files are not moved and processed twice (this should be fixed soon, testing right now)
- processing multiple files right now makes them output with the same name (iteration, carrier and ms) therefore this also results in multiple database entries
