### ISSUE TITLE
ENHANCEMENT: If there is no data loaded, CircleView is blank

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#37]
Hey guys,

if there is no data in the database the circle view looks like this:

![image](https://cloud.githubusercontent.com/assets/18442099/15632297/d9056a12-258d-11e6-836a-1077e9be10e5.png)

I would suggest that there should be a message like:

"No data yet synchronized" or something like this.

**Comment by deadlmaster** [comment]
what exactly do you mean with no data? amountOfCarrier? avg energy for each carrier? Right now the circles will be created by the variable amountOfCarriers.

**Comment by ghost** [comment]
The variable amountOfCarriers is known from the beginning, why does the circle page appear empty then?

**Comment by danielreischl** [comment]
After building the database is empty. It takes 60 seconds until the script reads in for the first time data out of the database. This means 60 seconds the variable amountOfCarriers isn't getting any value.

**Comment by ghost** [comment]
@AMOSus I cannot confirm this. I just deployed and went to the test website right away, circles were there from the beginning.

**Comment by danielreischl** [comment]
@Inkibus 

Just tested it. Deploy on Jenkins, wait a few seconds until its really deployed and you see that there are no circles. Just after 60 seconds the circles are shown.

**Comment by danielreischl** [comment]
> The variable amountOfCarriers is known from the beginning, why does the circle page appear empty then?

And this isn't the case anymore as stated in the standup email. Amount of Carriers is now dynamically created out of the database based on the session. 

Also look at this commit:

https://github.com/AMOSus/amos-ss16-proj6/commit/bc5ad7686ed622a18a4618e21ee08e21cbc61369

**Comment by ghost** [comment]
@AMOSus Ok you convinced me. This should not be our highest priority however.

**Comment by danielreischl** [comment]
with you but could be a user story in one of the next sprints @alexklar @abhinavpuri

**Comment by abhinavpuri** [comment]
Noted :+1:

**Comment by danielreischl** [comment]
Turned out to be a new user story. Think this issue can be closed.
