### ISSUE TITLE
LogFile path is never right

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#38]
Hey guys,

locally everything works fine, but on the deploy server django all of the time says that it cant find the logfile:

![image](https://cloud.githubusercontent.com/assets/18442099/15632328/63d0c6aa-258e-11e6-876f-414af2377b5a.png)

Any idea what I am doing wrong right now?

**Comment by ghost** [comment]
Maybe you can describe how you are trying to obtain the log file?

**Comment by danielreischl** [comment]
From views.py. In the end it's just about the path. Locally everything is working with a local path.

views.py is in srv/django/dataInterface and the Logfile is in srv/DataProcessing. I also tried the path srv/DataProcessing/dataProcessing.log. This is also not working. Don't know why.

**Comment by danielreischl** [comment]
Thx @TobiDo

**Comment by TobiDo** [comment]
De nada. :-)
Just two remarks: 
1) I would discourage using relative paths. The base directory for relative paths is not the directory where the file, in this case views.py, lies in. It is rather the directory from which the script is called: I would suppose it's /srv/Django in this case, but I am not quite sure.
2) Absolute paths have to start with '/'.

**Comment by danielreischl** [comment]
ah okay makes sense :) Thanks again :) Didn't know both of it :+1:
