### ISSUE TITLE
REFACTORING Frontend

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#42]
In the fronted a lot of refactoring has to be done to enhance readability and maintainability. A lot of the graph and variable names do not resemble the current wording in the glossary anymore. Also more of the text could be documented.

**Comment by deadlmaster** [comment]
Yes I agree with that. Will refactor the code after everything is working.

**Comment by ghost** [comment]
Totally understand, lets finish the functionality first ;)

**Comment by danielreischl** [comment]
#35 and #26  are also topics for that

**Comment by abhinavpuri** [comment]
I do agree. Currently there are some inconsistencies. We will also update the Product Glossary to reflect the current terminology being used

**Comment by ghost** [comment]
this is getting worse and worse .. we need to do something 🙈

**Comment by ghost** [comment]
I think it has improved a lot and there will not be any more time for further refactoring.
