### ISSUE TITLE
Replacement of Checkboxes

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#43]
Hey guys,

after seeing the first drafts I figured that the checkboxes are taking away a lot of space. So I was thinking why are we not replacing them by something like this: (It's just a paint draft. So don't judge me pls)

![image](https://cloud.githubusercontent.com/assets/18442099/15634665/c925fc38-25c9-11e6-9e7f-1feb6c9f8365.png)

On pressing on one of the buttons they are getting highlighted with another colour and in this way selected. Hopefully you get my draft :D

What do you guys think?

**Comment by TobiDo** [comment]
That's a good idea, I think. I will prepare an implementation of your sketches. However today I don't have much time, but it should be ready until tomorrow evening.

**Comment by abhinavpuri** [comment]
@AMOSus - the draft makes sense. If possible, you can go ahead with this implementation in this current sprint. If not, we can add this correction as a new user story for the next sprint

**Comment by deadlmaster** [comment]
Yep good idea, the carriers to take too much space. My idea was to just placethem left of the graph. But we could also do it like you drew.

**Comment by danielreischl** [comment]
Hm... I don't think this is a small task which we can add to this sprint easily. I think this is a new userstory. Especially because non? of the current userstories are done as far as I know. Only  US39 is more or less done right now.

If you guys @abhinavpuri @alexklar decide that we will implement it and make it a high priority in the product backlog then I think @TobiDo can go ahead and do so work on it but without the need to finish it until Wednesday. But also just if he has the capacity and the assigned user stories are done. 

In addition, if you agree on @alexklar @abhinavpuri we can skip implementing the dropdown instead as acceptance criteria for US83 and US34. But this decision is up to you guys :)

**Comment by abhinavpuri** [comment]
@AMOSus I am personally in favor of the drop-down because of how we visualized it. So that should rather stay as acceptance criteria.  However, this suggestion of yours is definitely worth a user story and even I feel this should be given high priority for coming sprint

**Comment by alexklar** [comment]
@all: we just discussed it and we are now defining an alternative checklist visualization in a new user story for the next sprint.

**Comment by danielreischl** [comment]
That's great :+1:
