### ISSUE TITLE
Label does not change, when selecting different dimension.

### ISSUE THREAD

**Issue by deadlmaster** [AMOSus/amos-ss16-proj6#46]
Hey guys,
need some insight on this matter. The code is in the main.ctrl..js file.

![image](https://cloud.githubusercontent.com/assets/9768935/15636155/31a10470-25f6-11e6-8663-b4024c2ea009.png)

When a new dimension is selected, the query statement will change ( this works!) but it also should change the label of the y-axis of the graph. Right now, it is not working. Anyone has an idea?

![image](https://cloud.githubusercontent.com/assets/9768935/15636163/6f5d9b0c-25f6-11e6-8260-f8e0aa368739.png)

the picture above shows the variable, containing the string to be displayed.

**Comment by AMOSus** [comment]
I have no real clue but I would guess it is somewhere here:

![image](https://cloud.githubusercontent.com/assets/18442099/15636250/f408d004-25f8-11e6-99e3-ad3f1ea81602.png)

You have on the top scope.dimension and a bit deeper scope.selectedDimension.

I have the feeling that this is the reason. Might be complete BS but this would be my first guess.

**Comment by danielreischl** [comment]
@TobiDo did your commit fix it?

**Comment by TobiDo** [comment]
I think so. But I also now made the heading change. After testing this, I'm going to close it.

**Comment by TobiDo** [comment]
Okay, fixed. Heading also does change now.
I also did some small refactoring.

**Comment by deadlmaster** [comment]
The graph is not plotted when a selection of carriers and dimension is made. I get the following error now: 

![image](https://cloud.githubusercontent.com/assets/9768935/15653315/9c0974aa-268c-11e6-80f2-4ef49d1d9aab.png)

EDIT: okay the fault was on my side

**Comment by deadlmaster** [comment]
The labels are changing, but if you select average acceleration from the dropdown menu, the label changes to "undefined undefined"

![image](https://cloud.githubusercontent.com/assets/9768935/15653852/f2797364-268f-11e6-9297-c67d9270c92d.png)
