### ISSUE TITLE
BUG: Carriers and dimension are not preselected

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#47]
If you are going to the Average Consumption Chart from the circle view, the values are not preselected. This confuses me everytime as a user.

![image](https://cloud.githubusercontent.com/assets/18442099/15650885/158638d8-267c-11e6-825d-de5a24457f58.png)

**Comment by deadlmaster** [comment]
Not a bug but intentional. 
_Also notice_: If the user is selecting carriers and hits refresh, the checkboxes get deselected!

In my opinion the functionality is better this way. Take the scenario that the user selected 10 carriers, but decides later that he wants only to see 1. In your use case he would have to deselect 9 carriers first.

**Comment by danielreischl** [comment]
I think both functionalities should be changed. As a user I often just want to change the dimension if I am comparing several carriers and don't want to reselct them. Especially it's kind hard to remember which of the carriers I selected. 

Also I might want to compare instead of 1,4,5 1,4,8. So I have to reselect all of them. 

I don't think that it would be a comon usecase that a user just randomly selects carrier ids. He is coming all of the time from thie cirlce view and so I think he wants to see the pre selection

**Comment by deadlmaster** [comment]
> Especially it's kind hard to remember which of the carriers I selected.

Well you can see in the graph legend, which carriers you see right now.

> Also I might want to compare instead of 1,4,5 1,4,8. So I have to reselect all of them.

I knew you would say that! Yes, it can be seen on both ways. Either the user wants to make a small change or a big one. We have to decide which approach is the most convenient one for the user.

> I don't think that it would be a comon usecase that a user just randomly selects carrier ids. He is coming all of the time from thie cirlce view and so I think he wants to see the pre selection

Why randomly? He chooses carriers he wants to compare with in the circleview or barview and gets redirected to the graph. The graph will display instantly the selected carriers in the graph. The user does not need to check the carriers again.

**Comment by danielreischl** [comment]
I just tested again how I would use the tool:
1. I look at the circle view and select red carriers and maybe a green one.
2. Go to average energy consumption graph
3. Wants to see instead of energy consumption, average speed to see if this caused the increase in energy consumption
4. go back to the energy consumption
5. Maybe adding other carriers instead and do 2-4 again.

I think if it is preselected it improves the user experience a lot. 

> Well you can see in the graph legend, which carriers you see right now.

That't true but also just if I'm hoovering at the graph. But I doubt the user want to look it up all of the time.

I get your points. Why are we not just adding a "remove Filters" button and everything is getting deselected?

**Comment by TobiDo** [comment]
I agree, that it would be more convenient if selection was not deleted. Even if I just change dimensions I have re-select the carriers each time.

I also agree that a "reset"/"remove Filter" button would be the better choice.

**Comment by deadlmaster** [comment]
Ya the reset button would make sense. I will look into this, but i can not promise to finish it tonight

**Comment by danielreischl** [comment]
Yeah, I rather think this would be a new user story. Don't think this has to be done on the fly @alexklar @abhinavpuri

**Comment by ghost** [comment]
Actually I always expect the carriers to be selected still (so you also see which carriers it shows after refreshing the graph) and I though the disappearing checkboxes of selected carriers was a bug too. I would leave them selected.

**Comment by alexklar** [comment]
New user story is being generated. Thanks for the feedback!
