### ISSUE TITLE
circle carrier display.

### ISSUE THREAD

**Issue by deadlmaster** [AMOSus/amos-ss16-proj6#48]
Hey guys,
I would like to inquire the threshold value of the circle colors. As you know, we calculate the percentage with this formula 

> The values are calculated by the Total Energy Consumption of the last iteration divided by the Total Energy Consumption of the first iteration

Most of the real data now shows, that the percentage are between 94% to 106%. 

My suggestion would be:

red = everthing over 105%
yellow = 95%-100% 
green = under 95%

**Comment by danielreischl** [comment]
I would rather suggest:

red = everthing over 105%
yellow = 100,0001%-105% 
green = under incl. 100%

I think everything that is below and at hundred green. We want to determine an increase in energy consumption. 100 should still be green because there is no inncrease in energy consumption

**Comment by deadlmaster** [comment]
I have to correct myself. Yellow was meant to be 95% to 105%

My idea was, that everything between 95% to 105% is normal and therefore should be indicated by yellow. It is like a tolerance range set by us. Green would therefore be especially good.

But your idea also would make sense. Everything below 100% is already less energy consumption which is good. We can go with your idea first and try it out. 

Other opinions?

**Comment by danielreischl** [comment]
Just a small addition:

Out of my experiences at big companies, always use green if there is no reason to worry. Yellow already indicates a possible problem and if something is red it means shut everything down.

**Comment by deadlmaster** [comment]
Ya right. In that sense, is the color yellow even needed here?

**Comment by danielreischl** [comment]
I would keep it. Yellow can be used as an indicator for a contamination

But after thinking a bit longer about this issue I would maybe even keep green until 102,5. Just because the energy consumption goes up slightly it doesn't mean that there is a contamination. Yellow between 102,5 and 105 percent. Red starting with 105 percent. But I'm not really sure.

**Comment by deadlmaster** [comment]
^ That approach sounds good to me as well. I will implement it like that if the others are okay with it :)

**Comment by danielreischl** [comment]
@abhinavpuri  @alexklar 

As POs you should give feedback :) Maybe you guys already talked with the industry partner about it.

**Comment by alexklar** [comment]
Since the data we have is like this: 

> Most of the real data now shows, that the percentage are between 94% to 106%.

I think it makes sence to have:
Green: <=102.5%
Yellow: >102.5% and <=105%
Red: >105%
