### ISSUE TITLE
Data fluctuation during start up.

### ISSUE THREAD

**Issue by deadlmaster** [AMOSus/amos-ss16-proj6#49]
Hey guys,

during a new start of the page, I noticed that the data is changing rapidly. Every time I switch between the circleView and other views, the percentage on the circle changed. After some minutes the fluctuation stops and the percentage stays the same. 

Anyone else saw this issue?

![image](https://cloud.githubusercontent.com/assets/9768935/15657074/ea0c9ecc-26ad-11e6-8b31-3e5cf44dc492.png)

![image](https://cloud.githubusercontent.com/assets/9768935/15657084/f3c054b8-26ad-11e6-9dac-8112d4e713c4.png)

![image](https://cloud.githubusercontent.com/assets/9768935/15657093/00ca9718-26ae-11e6-90a8-0e6ce5b6e8a7.png)

![image](https://cloud.githubusercontent.com/assets/9768935/15657096/0a7d3aa4-26ae-11e6-8c10-95d1aee37566.png)

**Comment by TobiDo** [comment]
The dataProcessing that happens each time we start up the container just takes some time. We can try to make it quicker, but I would actually not call it a bug.

**Comment by danielreischl** [comment]
That's on purpose. It simulates the "real time data". After a few minutes we don't have any new data and the simulation stops. And I would keep it that way for demonstration purposes. Because our tools shouldn't just display static data.

**Comment by danielreischl** [comment]
But I think this can also be closed :)

**Comment by TobiDo** [comment]
Ah, right. I forgot about this real time stuff.
Would anyone mind if we disable it for the moment? It is slightly annoying while testing.

**Comment by deadlmaster** [comment]
@AMOSus ah okay I see. But is it not kind of useless now? Because in order to see it you have to change the view all of the time...

**Comment by danielreischl** [comment]
why? Just press the refresh button. And this is one of the highest prioritized backlog items. If we change it, we have to change it back again next week.

**Comment by deadlmaster** [comment]
we dont have any refresh button right now... that is why i am saying it is kind of useless **now**

**Comment by danielreischl** [comment]
I was talking about the browser refresh button :)

**Comment by deadlmaster** [comment]
Ahh okay, yes that should work. :smile: 
Anyway the question got solved, so it can be closed now.
