### ISSUE TITLE
Jenkins is not loading the latest github push?

### ISSUE THREAD

**Issue by deadlmaster** [AMOSus/amos-ss16-proj6#50]
Hey guys,

the current deployed build on the test server, does not have code that was already pushed in github and passed the travis build.

I checked the files main.ctrl.js in the github repository and the main.ctrl.js on the test server and they are not the same.

Is it only me? I am missing the iteration dropdown menu on the test-server

**Comment by danielreischl** [comment]
just rebuild in travis and jenkins. might just be some issue with travis and jenkins.

**Comment by danielreischl** [comment]
its working now
