### ISSUE TITLE
Anomalies in position data

### ISSUE THREAD

**Issue by TobiDo** [AMOSus/amos-ss16-proj6#51]
If you look at the position data in the continuous energy graph, you will see that (in some iterations) there are drops of the position: they seem to jump back to the beginning of the line only to return to their previous position shortly afterwards.
While I cannot exclude completely the possibility that this error is caused by the way we fetch (and join) the data from the database, I strongly suppose that this problem is concerned with either the initial processing or the storing to the database. (Another possibility would be that the original data is inconsistent)

Taking a closer look at the data points, I suppose that the data point is actually "correct" -- it is just divided by _1000_. Any ideas why this happens?

**Comment by ghost** [comment]
You are right. I just looked at the data right after the initial processing and found these values in some of the CSV files. So the problem occurs right during the initial processing. I don't have any idea right now why this happens. I will need to take a deeper look.

<img width="390" alt="bildschirmfoto" src="https://cloud.githubusercontent.com/assets/18442111/15703687/f92c012e-27e6-11e6-9603-b49278081072.png">

**Comment by abhinavpuri** [comment]
As I see it right now, we can accept this user story since the acceptance criteria defined by us did not factor in such a scenario (we could not have seen this coming :P )
However, we cannot show it as it is to the industry partner. So we should definitely be looking to correct it. As it stands, we will add this as a bug which would be nice if implemented before the industry partner meeting

**Comment by ghost** [comment]
I have a feeling that these drops in the position occur when the timestamp is actually not in the data and has to be interpolated. Maybe there is something wrong with the equation. Will check that tomorrow.

**Comment by danielreischl** [comment]
Update on this one:

This is always happening if a carrier is moving from one drive to another. The compression part in compressInitialData isn't working properly.

**Comment by ghost** [comment]
Well as far as we know now there are two sides to this
1 compressInitialData has sometimes (NOT always!) a little bit lower (as seen in the picture) now values when a carrier is switching drive
2 The displayed values of the position however seem to be much lower than the problem 1. The values in problem one seem to be up to 1/6 of the correct value. However the position drops that can be seen on the graph page are about 1/1000 of the correct value. This problem may occur somewhere else, or it may be resolved when 1 is resolved.

**Comment by ghost** [comment]
So I will take over for 1 and then we will see.

**Comment by danielreischl** [comment]
> Well as far as we know now there are two sides to this
> 1 compressInitialData has sometimes (NOT always!) a little bit lower (as seen in the picture) now values when a carrier is switching drive
> 2 The displayed values of the position however seem to be much lower than the problem 1. The values in problem one seem to be up to 1/6 of the correct value. However the position drops that can be seen on the graph page are about 1/1000 of the correct value. This problem may occur somewhere else, or it may be resolved when 1 is resolved.

No, it's kinda easy to see that it is just compressInitialData which causes the problem:
1. The drops are not random. They are dropping even for different carriers all more or less at the same timestamp. Would make sense that there is a drive change.
2. The data is nowhere touched anymore. It is handled as a float from the compression-Script until the csv creation
3. I just looked up one more drop which you are already seeing in the output from compressInitialData. This is not a casting issue at some other point.

![image](https://cloud.githubusercontent.com/assets/18442099/15816561/941ef7b4-2bd3-11e6-8d51-ad36c08a9bee.png)
![image](https://cloud.githubusercontent.com/assets/18442099/15816574/a526203c-2bd3-11e6-8b53-b67815407c67.png)

**Comment by danielreischl** [comment]
@Inkibus : If you are doing it, can you please also refactor the compression in a way that it is testable and write tests that are covering this issue? I think the compression is such an essential part, that we should have a proper test coverage for that.

**Comment by ghost** [comment]
Fixed with 505532f.
