### ISSUE TITLE
Selection of a carrier

### ISSUE THREAD

**Issue by deadlmaster** [AMOSus/amos-ss16-proj6#52]
Hey guys, 

the checkboxes look good now :+1: 

I just have one suggestion. Right now, it is hard to distinguish between selected checkboxes and not selected checkboxes, since only the font of the text gets a little thicker. For example in the picture below, 3 and 8 are selected.

![image](https://cloud.githubusercontent.com/assets/9768935/15801837/c5b00454-2aa1-11e6-8f72-477c03a0ae55.png)

How about changing the border color instead?

**Comment by danielreischl** [comment]
Yeah that's a good idea. I would even suggest to mmake the regular border colour gray or not existing at all and then just adding it by selecting.

**Comment by abhinavpuri** [comment]
Yes it should be highlighted better. Difficult to make out selection currently :)

**Comment by abhinavpuri** [comment]
So could anyone work on this?

**Comment by danielreischl** [comment]
Don't think this will happen in this sprint anymore. Rather make a new user story out of it for next sprint.

**Comment by TobiDo** [comment]
Yes, and/but the user story should mostly be about coming up with a good design. The technical part is very easy - only the main.css file has to be touched. Btw. the border color _is_ changing already. The border is just very thin right now. :-)

**Comment by deadlmaster** [comment]
Closed, issue is already fixed with ec9cef2
