### ISSUE TITLE
Chart-Angular.js - What is it doing?

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#53]
Hi guys,

what is this file doing?

![image](https://cloud.githubusercontent.com/assets/18442099/15805059/ec8456b2-2b1d-11e6-8e12-b41ef92ab2b3.png)

I'm confused. Is this a lib we are using or is it something else? And if it is a lib why isn't it in the BoM?

**Comment by danielreischl** [comment]
If nobody is using, needing it, I will just delete it.

**Comment by ghost** [comment]
Did you already delete it?

**Comment by danielreischl** [comment]
Nope

**Comment by deadlmaster** [comment]
It is needed for the bar chart. This is the library Shefali and Vick used. Thought it would be already integrated with bower install?

**Comment by ghost** [comment]
Is this still an open issue?
