### ISSUE TITLE
BUG: CEC is destroyed

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#54]
Hi guys,

one of the commits destroyed the Continouse Energy Consumption Chart. 

![image](https://cloud.githubusercontent.com/assets/18442099/15805292/ff992964-2b25-11e6-85dc-7538e326e73a.png)

Can someone have a look at it? It was working great yesterday.

**Comment by abhinavpuri** [comment]
@AMOSus : I believe it is destroyed since last night. I checked the site late last night and the view was the same. I assumed that you guys are working on it so did not comment at that moment.
