### ISSUE TITLE
Optimizing Graph layout on both graph pages

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#56]
The graph sizes is not optimal on both graph pages.. ideally the user shouldn't need to scroll for seeing all features (selection, graph and legend(e?)).

We somehow should align the layout of the graph with the current screen size of the user? Any ideas on that?

**Comment by abhinavpuri** [comment]
@Inkibus : Any progress on that? This is a user story in the current sprint (to avoid page scrolling)

**Comment by ghost** [comment]
Wow actually i just now saw that this is assigned to me. During the meeting I told everyone that I don't want to do it because I don't have any clue about it. I can try to do stuff..

**Comment by danielreischl** [comment]
Well it is a userstory, so close for now.
