### ISSUE TITLE
Center numbers in carrier selection

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#57]
Just a minor thing. I think it would look more beautiful if the numbers in the carrier selection were centered. As seen in this picture they are left aligned right now.
<img width="276" alt="bildschirmfoto 2016-06-05 um 21 00 11" src="https://cloud.githubusercontent.com/assets/18442111/15807588/68f9ad0c-2b62-11e6-940f-924aa7e36752.png">

**Comment by TobiDo** [comment]
Oh, I forgot. That was solved with commit 26b7c6c.
