### ISSUE TITLE
More space between side bar ICONS and DESCRIPTION

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#58]
Right now there is very little space between the side bar ICONS and DESCRIPTION once you extend it. A little more space would make it look nicer in my opinion. Attached a picture here:
<img width="217" alt="bildschirmfoto 2016-06-05 um 21 00 15" src="https://cloud.githubusercontent.com/assets/18442111/15807598/99182b94-2b62-11e6-84eb-ba66fc47db98.png">

**Comment by ghost** [comment]
The "HOME" seems fine because the logo give more room until the text starts. On the other items however, there is very little space between the icons and the text.

**Comment by deadlmaster** [comment]
![image](https://cloud.githubusercontent.com/assets/9768935/15807857/7438251c-2b68-11e6-8ffe-67185ee8d450.png)
