### ISSUE TITLE
Barchart increases layout size after refresh

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#63]
I added the refresh button that just calls the draw function on the bar chart. When its redrawn, its suddenly way bigger than before. I don't know why this happens.

@deadlmaster maybe you can have a look

**Comment by deadlmaster** [comment]
I will take a look at it

**Comment by ghost** [comment]
@deadlmaster any input on this?

**Comment by deadlmaster** [comment]
@AMOSus @alexklar @abhinavpuri @TobiDo 

Do you other guys have the same problem?  For me, the graphs are not getting bigger at all?

**Comment by ghost** [comment]
This is how it looks for me on Google Chrome iOS. @AMOSus  @alexklar @abhinavpuri @TobiDo  could you please check.

Before refresh (just navigated to the page):
<img width="1281" alt="bildschirmfoto 2016-06-21 um 13 05 05" src="https://cloud.githubusercontent.com/assets/18442111/16227447/d9372388-37b0-11e6-8fcb-2eda75250ac7.png">

After refresh:
<img width="1279" alt="bildschirmfoto 2016-06-21 um 13 05 12" src="https://cloud.githubusercontent.com/assets/18442111/16227446/d9345e00-37b0-11e6-8dab-15d33c5f76d4.png">

**Comment by deadlmaster** [comment]
I tried it on my iPad and it changed the size as well... That is really weird. Right now I have no clue what the cause for this issue might be, because the refresh code does only call the function again. There shouldn't be any error :confused:  Will update, if I find something

**Comment by ghost** [comment]
fixed with 1871ae1
