### ISSUE TITLE
Consistent colors for carrier energy consumption on all charts

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#64]
Color in the graph pages should be the same as in the bar chart and the circle carrier view.

For me the cyan was fine for low energy consumption and the other colors too.

@AMOSus changed it to green in the graph views.

@deadlmaster , @abhinavpuri, @alexklar, @TobiDo any input?

**Comment by ghost** [comment]
<img width="767" alt="bildschirmfoto 2016-06-21 um 00 12 32" src="https://cloud.githubusercontent.com/assets/18442111/16211904/e2f87b5e-3744-11e6-9fe9-bc3bd3187d9b.png">
<img width="231" alt="bildschirmfoto 2016-06-21 um 00 12 26" src="https://cloud.githubusercontent.com/assets/18442111/16211905/e3114170-3744-11e6-8c3d-7fc6378ca14b.png">
<img width="822" alt="bildschirmfoto 2016-06-21 um 00 12 55" src="https://cloud.githubusercontent.com/assets/18442111/16211915/ef48edf8-3744-11e6-8d6d-0b013c405588.png">

**Comment by danielreischl** [comment]
also here:

![image](https://cloud.githubusercontent.com/assets/18442099/16212079/be520116-3745-11e6-9a7f-e90eee03abca.png)

But I think the whole page should mostly get a design upgrade.

**Comment by deadlmaster** [comment]
Why would you change the whole design now? The green was good. This cyan now does not fit with the other colors. Same goes with the checkboxes. They had the same color as the circle and bar view page! 

I agree with the buttons on the homepage though,. they need to fit the rest

**Comment by ghost** [comment]
This is fixed
