### ISSUE TITLE
Graphs still too big (Circles, continuous, average)

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#66]
The industry partner said today that he doesn't want any scrolling at all. Therefore, we still need to decrease the size of the graphs.

**Comment by ghost** [comment]
maybe we need another user story for this @abhinavpuri @alexklar

**Comment by abhinavpuri** [comment]
@Inkibus : we already had a user story to to remove the scrolling but I think we accepted it inspite there being some scrolling. Will add it again as a bug in that :)
