### ISSUE TITLE
Sometimes no values (only for the circle graph?) displays

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#67]
I think this happens when the internet connection is too slow, so that 1 second (which is currently set as wait time for the data to load until the circles are drawn) is too little time. @alexklar and me experienced this today in the university where the connection was really bad.

Either more wait time would be good or we need to find a workaround. Maybe a loop that checks if the data is loaded or not. The loop may also cause problems, if a file with empty data is requested. Here a maximum number if tries (maybe like 5 -> 5 seconds or something) should be determined. What do you guys think?

**Comment by danielreischl** [comment]
This belongs to #55
