### ISSUE TITLE
Make flex page available from circle page.

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#69]
right now when flex page is entered no carrier is preselected and no graph is shown. To compensate that we could also make it accessible from the circle page. What do you think?

**Comment by ghost** [comment]
<img width="1599" alt="bildschirmfoto 2016-06-22 um 10 08 34" src="https://cloud.githubusercontent.com/assets/18442111/16259103/4deaa06e-3861-11e6-99b4-09523eec1836.png">

**Comment by ghost** [comment]
User story for this? @abhinavpuri @alexklar

**Comment by abhinavpuri** [comment]
@Inkibus : there's a user story in the product backlog already for a few weeks now, regarding a toggle button between continuous and average energy charts. We will just add this to that story, which allows the user to move between all the 3 views
