### ISSUE TITLE
All Changes from now on mobilefriendly?

### ISSUE THREAD

**Issue by danielreischl** [AMOSus/amos-ss16-proj6#72]
Hey,

why are wo not making all changes to the front end from now on mobilefriendly? This works so easily with bootrap and would avoid a lot of work in the end. It is just using the bootrap grid system:

https://getbootstrap.com/examples/grid/

xl = display on large screens
md = medium
sm = tablet
xs = smartphone

It is kinda easy. Just look at the simulation page which is already in the system.

Any thoughts?

**Comment by ghost** [comment]
I don't think this is an issue regarding a current problem or something that needs to be changed now? It is rather a strategic decision for the future. Should we close this?
