### ISSUE TITLE
Obtaining canvas elements in circle page returns "null" 

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#73]
Hi,
I implemented a functionality that redraws the selection circles on the canvas circles on the circle page when 
1: The page is refreshed
2: The circles are redrawn when switching the two contamination measures
Whenever this is done however i can't get a hold on the elements. Maybe you see the mistake here. The rest should work so far..
<img width="1679" alt="bildschirmfoto 2016-06-26 um 13 25 45" src="https://cloud.githubusercontent.com/assets/18442111/16361992/e87a7148-3ba1-11e6-92e3-18e6bf211bda.png">
<img width="1680" alt="bildschirmfoto 2016-06-26 um 13 26 09" src="https://cloud.githubusercontent.com/assets/18442111/16361993/e8975420-3ba1-11e6-9301-f34c1812d74e.png">
@deadlmaster @TobiDo @AMOSus

**Comment by ghost** [comment]
One more thing: The normal selection of the carriers that is now also done in the drawSelectionOnCarrier() method (the same method that throws the error when refreshing or switching). But the normal selection works fine.

**Comment by danielreischl** [comment]
http://stackoverflow.com/questions/6796194/canvas-getcontext2d-returns-null

![image](https://cloud.githubusercontent.com/assets/18442099/16362327/9eb08a92-3bac-11e6-9ea4-26f25feee57a.png)

We are also drawing on init, right?

**Comment by ghost** [comment]
Not the getConetext('2d') returns null, the getElementById returns null (one line before) thats why getConetext('2d') can't be called on null

**Comment by ghost** [comment]
And well the circle selection (redrawAllSelections();) now is drawn after the creation of the canvas ($scope.circleGraph();)

<img width="876" alt="bildschirmfoto 2016-06-26 um 15 04 06" src="https://cloud.githubusercontent.com/assets/18442111/16362440/3f58753e-3baf-11e6-92f4-ad7d9bad9938.png">

**Comment by ghost** [comment]
Kann es sein dass man an die canvas Elemente danach nicht mehr einfach so ran kommt da sie dynamisch im code erzeugt werden? ich umgehe das jetzt mal indem ich direkt beim zeichnen auch die kreise zeichnen lasse. da müssten die Elemente auch noch da sein.

**Comment by ghost** [comment]
exactly this was the problem. sorry for german. The problem was that the canvas elements can only be accessed while the creating code is still running (only calling in the method that is also creating them). OR in the case of an event (when clicking on them). fixed with fff1338
