### ISSUE TITLE
Percentage Data Service

### ISSUE THREAD

**Issue by deadlmaster** [AMOSus/amos-ss16-proj6#74]
Hi guys,
I am out of ideas on how to solve the circle view issue. Maybe you have some idea?
It is about the following problem:
I identified the problem, why the circle carrier page is sometimes empty and sometimes showed the past data set when you change the contamination type:

The reason is, that the percentage array is sent right away to the caller, without waiting for the parse function!

![image](https://cloud.githubusercontent.com/assets/9768935/16394321/e230f28a-3cb4-11e6-9823-234eb032347d.png)

I already tried to work with timeout but this does not really work. 
What I want is a callback function, that checks if the parsing has completed. Then the array can be sent to the caller and the circles can start to be drawn. Anyone an idea how to implement that in javascript?

**Comment by danielreischl** [comment]
Tobi and I just discussed it. There are is one workaround for now in my opinion:

Get the CSV-File before parsing it. So the csv file should already be available.

Better Solution:

Change of CSV File to a JSON File and so there would be no more a need to use Papaparse:

https://docs.python.org/2/library/json.html

**Comment by danielreischl** [comment]
And the quickest Workaround would be to load the percentageservice on every page. Wouldn't really fix it, but would seem like it would be fixed :D

**Comment by deadlmaster** [comment]
okay thanks for the hints, will take a lookt at it. If you have anything else, feel free to post it here . Will close the issue once it works somehow.

**Comment by deadlmaster** [comment]
done by @TobiDo  with 741d368 and my commit with 1376002
