### ISSUE TITLE
Header font displayed wrong

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#75]
This is how my header looks like:

<img width="1440" alt="bildschirmfoto 2016-06-28 um 22 37 19" src="https://cloud.githubusercontent.com/assets/18442111/16431462/036158a6-3d81-11e6-99b4-4e6973073f48.png">
<img width="1440" alt="bildschirmfoto 2016-06-28 um 22 37 41" src="https://cloud.githubusercontent.com/assets/18442111/16431463/03615a04-3d81-11e6-9c21-d2f57adc7751.png">

What is causing this problem?

**Comment by danielreischl** [comment]
a wrong layout setup from the beginning. Look at #70 as a fix
