### ISSUE TITLE
Improve X Axis of Average and Continuous graph

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#80]
Maybe be should round the X axis values on both graph pages, because neither the timestamps of the cont. nor the iterations of the avg. graph are float numbers.

<img width="1560" alt="bildschirmfoto 2016-07-09 um 11 29 04" src="https://cloud.githubusercontent.com/assets/18442111/16707278/96cff6ac-45c8-11e6-8e71-2914d72e8633.png">

**Comment by deadlmaster** [comment]
:+1:  I think this is a great idea, as the in-between points do not look nice and are also not really needed.

**Comment by abhinavpuri** [comment]
Yeah this should be done :)

Is someone onto it?

**Comment by ghost** [comment]
I'm currently browsing documentations and forums regarding this ..

**Comment by ghost** [comment]
It works! got it, but for some reason now the graph goes into the left side of the page?

<img width="1642" alt="bildschirmfoto 2016-07-12 um 01 50 52" src="https://cloud.githubusercontent.com/assets/18442111/16750622/5b78ff74-47d3-11e6-8860-ef9af952845f.png">

**Comment by ghost** [comment]
Fixed with 25a5c79, c867ba5  and finally 4663647  in the row. But now we have the new issue, would leave this open until this is solved.

**Comment by ghost** [comment]
Would be good if someone could help me with this @AMOSus @TobiDo @deadlmaster.

**Comment by deadlmaster** [comment]
I took a look and did not find the cause of the problem, yet...

**Comment by ghost** [comment]
This happens on all pages for me now and doesn't have anything to do with the pushes i think. Do you have the same problems?
