### ISSUE TITLE
Button layout on circle page

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#83]
<img width="1435" alt="bildschirmfoto 2016-07-10 um 19 34 26" src="https://cloud.githubusercontent.com/assets/18442111/16715034/9facdb42-46d5-11e6-988c-59ffa4da4bbb.png">

I think these buttons should be separated by putting them in two rows.
Row 1 should contain switching between different circle views.
The Row 2 should redirect you to the different graphs.
In my opinion this makes sense as these are two different logics.

**Comment by abhinavpuri** [comment]
If someone has the time to take this up, then please go ahead. Otherwise, i would say it is not really a high priority story and should only be done once all other tasks are 100% complete

**Comment by danielreischl** [comment]
Im with you that these four buttons aree not fittig together, but two button rows below each other also confusig. This was a design mistacke kinda from the beginning. Different tabs or similar could change the issue.

**Comment by ghost** [comment]
It would be a good way to solve this issue, but since we won't have the time for this why not just make two rows?

**Comment by danielreischl** [comment]
Because it looks really weired thoug.
How about this alternative? At least the buttons are not merged together anymore?

![image](https://cloud.githubusercontent.com/assets/18442099/16773474/67a6a104-4858-11e6-81be-40ed561a8049.png)

**Comment by danielreischl** [comment]
We could also add an transfer button left to the circle header. Like the refresh icon. At least for switching between cont and creeping.

**Comment by ghost** [comment]
Or at least have the switching next to each other and the two graphs next to each other

**Comment by danielreischl** [comment]
Will do that later

Outlook for Android herunterladen

On Tue, Jul 12, 2016 at 6:06 PM +0200, "Rene Rathmann" notifications@github.com wrote:

Or at least have the switching next to each other and the two graphs next to each other

---

**Comment by danielreischl** [comment]
Fixed with 5cffa9901d4ca69d2d12fa2c7f15a727829181a9
