### ISSUE TITLE
Side Pane clips over page

### ISSUE THREAD

**Issue by ghost** [AMOSus/amos-ss16-proj6#84]
Hi, for me the side pane clips over the page on all pages.

<img width="723" alt="bildschirmfoto 2016-07-12 um 12 31 30" src="https://cloud.githubusercontent.com/assets/18442111/16764124/a4b99ec4-482c-11e6-8fb8-140024e8e111.png">
<img width="876" alt="bildschirmfoto 2016-07-12 um 12 31 18" src="https://cloud.githubusercontent.com/assets/18442111/16764125/a4baa0a8-482c-11e6-915e-aee8a202b2f9.png">

Was this introduced in recent commits? I see that @deadlmaster was doing something related to this.

**Comment by deadlmaster** [comment]
#68 known issue.

I identified the bug and made a fix for it, which will be in the next commit.

Angular JS has been updated from 1.5.6. to 1.5.7. automatically by BOWER.
This update did crash some elements, including the navigation and the tabs, so I had to build work around solutions.

Angular Material is only stable with Angular JS 1.5.5 right now (as seen on the page)

**Comment by ghost** [comment]
Oh, ok .. awesome, I didn't know you already are so far on this. So now I also gave you the glorious opportunity to close this issue with the commit. It will feel twice as good 💯 💃 😸
